# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox

import ApplicationManagement as am
import RegisterMenu, User_PartyList, Shop_ActivityList


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(470, 710)
        Dialog.setFixedSize(470, 710)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/Icon.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        Dialog.setWindowIcon(icon)
        font = QtGui.QFont()
        font.setFamily("ZCOOL QingKe HuangYou")
        font.setPointSize(12)
        Dialog.setFont(font)
        Dialog.setStyleSheet(
            "background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.353234 rgba(235, 255, 235, 255), stop:1 rgba(215, 215, 255, 255));")
        self.ltxt_email = QtWidgets.QLineEdit(Dialog)
        self.ltxt_email.setGeometry(QtCore.QRect(42, 361, 391, 41))
        self.ltxt_email.setStyleSheet("font: 12pt \"Bai Jamjuree\";\n"
                                      "border: 0px;\n"
                                      "border-bottom: 2px solid rgb(0, 154, 49);\n"
                                      "background-color: rgba(255, 255, 255, 0)")
        self.ltxt_email.setText("")
        self.ltxt_email.setObjectName("ltxt_email")
        self.ltxt_password = QtWidgets.QLineEdit(Dialog)
        self.ltxt_password.setGeometry(QtCore.QRect(40, 450, 391, 41))
        self.ltxt_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.ltxt_password.setStyleSheet("font: 12pt \"Bai Jamjuree\";\n"
                                         "border: 0px;\n"
                                         "border-bottom: 2px solid rgb(85, 85, 255);\n"
                                         "background-color: rgba(255, 255, 255, 0)")
        self.ltxt_password.setObjectName("ltxt_password")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(40, 330, 211, 31))
        font = QtGui.QFont()
        font.setFamily("ZCOOL QingKe HuangYou")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
                                 "color: rgb(0, 100, 76);\n"
                                 "font: 12pt \"ZCOOL QingKe HuangYou\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(40, 420, 211, 31))
        font = QtGui.QFont()
        font.setFamily("ZCOOL QingKe HuangYou")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
                                   "color: rgb(36, 36, 111);\n"
                                   "font: 12pt \"ZCOOL QingKe HuangYou\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(40, 250, 391, 61))
        self.label_3.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
                                   "color: rgb(0, 100, 76);\n"
                                   "font: 20pt \"ZCOOL QingKe HuangYou\";")
        self.label_3.setTextFormat(QtCore.Qt.AutoText)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.btn_login = QtWidgets.QPushButton(Dialog)
        self.btn_login.setGeometry(QtCore.QRect(40, 537, 391, 41))
        self.btn_login.setStyleSheet(
            "background-color:  qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.353234 rgba(0, 154, 49, 255), stop:1 rgba(85, 85, 255, 255));\n"
            "color: rgb(255, 255, 255);\n"
            "font: 12pt \"ZCOOL QingKe HuangYou\";\n"
            "border-radius: 10px;\n"
            "border: 2px solid qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.353234 rgba(0, 154, 49, 255), stop:1 rgba(85, 85, 255, 255));")
        self.btn_login.setObjectName("btn_login")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setEnabled(True)
        self.label_4.setGeometry(QtCore.QRect(140, 30, 191, 201))
        font = QtGui.QFont()
        font.setFamily("ZCOOL QingKe HuangYou")
        font.setPointSize(48)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n")
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("img/Icon.png"))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.btn_register = QtWidgets.QPushButton(Dialog)
        self.btn_register.setGeometry(QtCore.QRect(40, 590, 391, 41))
        self.btn_register.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
                                        "font: 12pt \"ZCOOL QingKe HuangYou\";\n"
                                        "color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.353234 rgba(0, 154, 49, 255), stop:1 rgba(85, 85, 255, 255));\n"
                                        "border-radius: 10px;\n"
                                        "border: 2px solid qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.353234 rgba(0, 154, 49, 255), stop:1 rgba(85, 85, 255, 255));")
        self.btn_register.setObjectName("btn_register")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.this_dialog = Dialog

        self.btn_login.clicked.connect(self.Login)
        self.btn_register.clicked.connect(self.Register)

    def Login(self):
        email = self.ltxt_email.text()
        password = am.ToMD5(self.ltxt_password.text())
        checkLogin, userData = am.CheckLogin(email, password)

        if checkLogin == "Player":
            am.ChangeWindowDialog(self.this_dialog, User_PartyList, passData=userData)
        elif checkLogin == "ShopOwner":
            am.ChangeWindowDialog(self.this_dialog, Shop_ActivityList, passData=userData)
        else:
            am.ShowMessageBox("Login", "Error !!\nEmail or Password Doesn't Match", QMessageBox.Critical)

    def Register(self):
        am.ChangeWindowDialog(self.this_dialog, RegisterMenu)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Board Game Community"))
        self.label.setText(_translate("Dialog", "Email"))
        self.label_2.setText(_translate("Dialog", "Password"))
        self.label_3.setText(_translate("Dialog", "Board Game Community"))
        self.btn_login.setText(_translate("Dialog", "Login"))
        self.btn_register.setText(_translate("Dialog", "Register"))


if __name__ == "__main__":
    import sys, os

    app = QtWidgets.QApplication(sys.argv)

    fontDatabase = QtGui.QFontDatabase
    CURRENT_DIRECTORY = os.path.dirname(os.path.realpath(__file__))
    font1Path = os.path.join(CURRENT_DIRECTORY, "fonts", "ZCOOLQingKeHuangYou-Regular.ttf")
    font2Path = os.path.join(CURRENT_DIRECTORY, "fonts", "BaiJamjuree-Regular.ttf")
    fontDatabase.addApplicationFont(font1Path)
    fontDatabase.addApplicationFont(font2Path)

    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
