# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/New_ShopOwner.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox

import ApplicationManagement as am
import Login, RegisterMenu


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(470, 710)
        Dialog.setFixedSize(470, 710)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/Icon.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        Dialog.setWindowIcon(icon)
        font = QtGui.QFont()
        font.setFamily("ZCOOL QingKe HuangYou")
        font.setPointSize(12)
        Dialog.setFont(font)
        Dialog.setStyleSheet("background-color: rgb(235, 235, 255)")
        self.label_1 = QtWidgets.QLabel(Dialog)
        self.label_1.setGeometry(QtCore.QRect(42, 20, 391, 61))
        font = QtGui.QFont()
        font.setFamily("ZCOOL QingKe HuangYou")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_1.setFont(font)
        self.label_1.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
                                   "color: rgb(36, 36, 111);\n"
                                   "font: 20pt \"ZCOOL QingKe HuangYou\";")
        self.label_1.setTextFormat(QtCore.Qt.AutoText)
        self.label_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_1.setObjectName("label_1")
        self.btn_confirm = QtWidgets.QPushButton(Dialog)
        self.btn_confirm.setGeometry(QtCore.QRect(42, 580, 391, 41))
        self.btn_confirm.setStyleSheet("background-color: rgb(85, 85, 255);\n"
                                       "color: rgb(255, 255, 255);\n"
                                       "font: 12pt \"ZCOOL QingKe HuangYou\";\n"
                                       "border-radius: 10px;\n"
                                       "border: 2px solid rgb(85, 85, 255);")
        self.btn_confirm.setObjectName("btn_confirm")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(40, 230, 211, 31))
        font = QtGui.QFont()
        font.setFamily("ZCOOL QingKe HuangYou")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
                                   "color: rgb(36, 36, 111);\n"
                                   "font: 12pt \"ZCOOL QingKe HuangYou\";")
        self.label_5.setObjectName("label_5")
        self.ltxt_shopName = QtWidgets.QLineEdit(Dialog)
        self.ltxt_shopName.setGeometry(QtCore.QRect(42, 120, 391, 41))
        self.ltxt_shopName.setStyleSheet("font: 12pt \"Bai Jamjuree\";\n"
                                         "border: 0px;\n"
                                         "border-bottom: 2px solid rgb(85, 85, 255);\n"
                                         "background-color: rgba(255, 255, 255, 0)")
        self.ltxt_shopName.setText("")
        self.ltxt_shopName.setObjectName("ltxt_shopName")
        self.ltxt_phone = QtWidgets.QLineEdit(Dialog)
        self.ltxt_phone.setGeometry(QtCore.QRect(40, 190, 391, 41))
        self.ltxt_phone.setStyleSheet("font: 12pt \"Bai Jamjuree\";\n"
                                      "border: 0px;\n"
                                      "border-bottom: 2px solid rgb(85, 85, 255);\n"
                                      "background-color: rgba(255, 255, 255, 0)")
        self.ltxt_phone.setObjectName("ltxt_phone")
        self.txt_address = QtWidgets.QTextEdit(Dialog)
        self.txt_address.setGeometry(QtCore.QRect(40, 260, 391, 81))
        self.txt_address.setStyleSheet("font: 12pt \"Bai Jamjuree\";\n"
                                       "border: 0px;\n"
                                       "border-bottom: 2px solid rgb(85, 85, 255);\n"
                                       "background-color: rgba(255, 255, 255, 0)")
        self.txt_address.setObjectName("txt_address")
        self.ltxt_email = QtWidgets.QLineEdit(Dialog)
        self.ltxt_email.setGeometry(QtCore.QRect(42, 370, 391, 41))
        self.ltxt_email.setStyleSheet("font: 12pt \"Bai Jamjuree\";\n"
                                      "border: 0px;\n"
                                      "border-bottom: 2px solid rgb(85, 85, 255);\n"
                                      "background-color: rgba(255, 255, 255, 0)")
        self.ltxt_email.setText("")
        self.ltxt_email.setObjectName("ltxt_email")
        self.ltxt_password = QtWidgets.QLineEdit(Dialog)
        self.ltxt_password.setGeometry(QtCore.QRect(40, 440, 391, 41))
        self.ltxt_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.ltxt_password.setStyleSheet("font: 12pt \"Bai Jamjuree\";\n"
                                         "border: 0px;\n"
                                         "border-bottom: 2px solid rgb(85, 85, 255);\n"
                                         "background-color: rgba(255, 255, 255, 0)")
        self.ltxt_password.setObjectName("ltxt_password")
        self.ltxt_confirmPassword = QtWidgets.QLineEdit(Dialog)
        self.ltxt_confirmPassword.setGeometry(QtCore.QRect(40, 510, 391, 41))
        self.ltxt_confirmPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.ltxt_confirmPassword.setStyleSheet("font: 12pt \"Bai Jamjuree\";\n"
                                                "border: 0px;\n"
                                                "border-bottom: 2px solid rgb(85, 85, 255);\n"
                                                "background-color: rgba(255, 255, 255, 0)")
        self.ltxt_confirmPassword.setObjectName("ltxt_confirmPassword")
        self.btn_back = QtWidgets.QPushButton(Dialog)
        self.btn_back.setGeometry(QtCore.QRect(362, 660, 91, 31))
        self.btn_back.setStyleSheet("background-color:  rgba(0, 0, 0, 0);\n"
                                    "color: rgb(200, 9, 19);\n"
                                    "font: 12pt \"ZCOOL QingKe HuangYou\";\n"
                                    "border-radius: 10px;\n"
                                    "border: 2px solid rgb(200, 9, 19);")
        self.btn_back.setObjectName("btn_back")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(40, 160, 181, 31))
        font = QtGui.QFont()
        font.setFamily("ZCOOL QingKe HuangYou")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
                                   "color: rgb(36, 36, 111);\n"
                                   "font: 12pt \"ZCOOL QingKe HuangYou\";")
        self.label_4.setObjectName("label_4")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(40, 90, 211, 31))
        font = QtGui.QFont()
        font.setFamily("ZCOOL QingKe HuangYou")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
                                   "color: rgb(36, 36, 111);\n"
                                   "font: 12pt \"ZCOOL QingKe HuangYou\";")
        self.label_2.setObjectName("label_2")

        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(40, 480, 211, 31))
        font = QtGui.QFont()
        font.setFamily("ZCOOL QingKe HuangYou")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
                                   "color: rgb(36, 36, 111);\n"
                                   "font: 12pt \"ZCOOL QingKe HuangYou\";")
        self.label_8.setObjectName("label_8")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(40, 340, 211, 31))
        font = QtGui.QFont()
        font.setFamily("ZCOOL QingKe HuangYou")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
                                   "color: rgb(36, 36, 111);\n"
                                   "font: 12pt \"ZCOOL QingKe HuangYou\";")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(40, 410, 211, 31))
        font = QtGui.QFont()
        font.setFamily("ZCOOL QingKe HuangYou")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
                                   "color: rgb(36, 36, 111);\n"
                                   "font: 12pt \"ZCOOL QingKe HuangYou\";")
        self.label_7.setObjectName("label_7")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.this_dialog = Dialog

        self.btn_confirm.clicked.connect(self.CreateNewShopOwner)
        self.btn_back.clicked.connect(self.OpenRegisterMenu)

    def CreateNewShopOwner(self):
        shopOwnerData = {'shopName': self.ltxt_shopName.text(),
                         'phone': self.ltxt_phone.text(),
                         'address': self.txt_address.toPlainText(),
                         'email': self.ltxt_email.text(),
                         'password': am.ToMD5(self.ltxt_password.text()),
                         'confirmPassword': am.ToMD5(self.ltxt_confirmPassword.text())}
        checkShopOwnerData, checkDetail = am.CheckNewShopOwnerData(shopOwnerData)

        if checkShopOwnerData:
            try:
                am.InsertNewShopOwner(shopOwnerData)
                am.ShowMessageBox("Create New Shop Owner", checkDetail, QMessageBox.Information)
                am.ChangeWindowDialog(self.this_dialog, Login)
            except:
                checkDetail = "Error !!\nCannot Create New Shop Owner !!\nPlease Try Again !!"
                am.ShowMessageBox("Create New Shop Owner", checkDetail, QMessageBox.Critical)
        else:
            am.ShowMessageBox("Create New Shop Owner", checkDetail, QMessageBox.Critical)

    def OpenRegisterMenu(self):
        am.ChangeWindowDialog(self.this_dialog, RegisterMenu)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Board Game Community"))
        self.label_1.setText(_translate("Dialog", "New Shop"))
        self.btn_confirm.setText(_translate("Dialog", "Confirm"))
        self.label_5.setText(_translate("Dialog", "Address"))
        self.btn_back.setText(_translate("Dialog", "Back"))
        self.label_4.setText(_translate("Dialog", "Telephone"))
        self.label_2.setText(_translate("Dialog", "Shop Name"))
        self.label_8.setText(_translate("Dialog", "Confirm Password"))
        self.label_6.setText(_translate("Dialog", "Email"))
        self.label_7.setText(_translate("Dialog", "Password"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
