# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/Shop_ActivityDetail.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox

import ApplicationManagement as am
import Shop_ActivityList, Shop_ActivityMember


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(470, 710)
        Dialog.setFixedSize(470, 710)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/Icon.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        Dialog.setWindowIcon(icon)
        font = QtGui.QFont()
        font.setFamily("ZCOOL QingKe HuangYou")
        font.setPointSize(12)
        Dialog.setFont(font)
        Dialog.setStyleSheet("background-color: rgb(235, 235, 255);")
        self.lbl_title = QtWidgets.QLabel(Dialog)
        self.lbl_title.setGeometry(QtCore.QRect(20, 20, 431, 61))
        font = QtGui.QFont()
        font.setFamily("ZCOOL QingKe HuangYou")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lbl_title.setFont(font)
        self.lbl_title.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
                                     "color: rgb(36, 36, 111);\n"
                                     "font: 16pt \"Bai Jamjuree\";")
        self.lbl_title.setTextFormat(QtCore.Qt.AutoText)
        self.lbl_title.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_title.setObjectName("lbl_title")
        self.btn_cancelActivity = QtWidgets.QPushButton(Dialog)
        self.btn_cancelActivity.setGeometry(QtCore.QRect(40, 600, 391, 41))
        self.btn_cancelActivity.setStyleSheet("background-color: rgb(200, 9, 19);\n"
                                              "color: rgb(255, 255, 255);\n"
                                              "font: 12pt \"ZCOOL QingKe HuangYou\";\n"
                                              "border-radius: 10px;\n"
                                              "border: 2px solid rgb(200, 9, 19);")
        self.btn_cancelActivity.setObjectName("btn_cancelActivity")
        self.btn_back = QtWidgets.QPushButton(Dialog)
        self.btn_back.setGeometry(QtCore.QRect(360, 660, 91, 31))
        self.btn_back.setStyleSheet("background-color:  rgba(0, 0, 0, 0);\n"
                                    "color: rgb(200, 9, 19);\n"
                                    "font: 12pt \"ZCOOL QingKe HuangYou\";\n"
                                    "border-radius: 10px;\n"
                                    "border: 2px solid rgb(200, 9, 19);")
        self.btn_back.setObjectName("btn_back")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(40, 300, 211, 31))
        font = QtGui.QFont()
        font.setFamily("ZCOOL QingKe HuangYou")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
                                    "font: 12pt \"ZCOOL QingKe HuangYou\";\n"
                                    "color: rgb(36, 36, 111);")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(40, 90, 211, 31))
        font = QtGui.QFont()
        font.setFamily("ZCOOL QingKe HuangYou")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
                                    "font: 12pt \"ZCOOL QingKe HuangYou\";\n"
                                    "color: rgb(36, 36, 111);")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(40, 160, 211, 31))
        font = QtGui.QFont()
        font.setFamily("ZCOOL QingKe HuangYou")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
                                    "font: 12pt \"ZCOOL QingKe HuangYou\";\n"
                                    "color: rgb(36, 36, 111);")
        self.label_12.setObjectName("label_12")
        self.label_14 = QtWidgets.QLabel(Dialog)
        self.label_14.setGeometry(QtCore.QRect(40, 230, 211, 31))
        font = QtGui.QFont()
        font.setFamily("ZCOOL QingKe HuangYou")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
                                    "font: 12pt \"ZCOOL QingKe HuangYou\";\n"
                                    "color: rgb(36, 36, 111);")
        self.label_14.setObjectName("label_14")
        self.lbl_date = QtWidgets.QLabel(Dialog)
        self.lbl_date.setGeometry(QtCore.QRect(40, 120, 391, 41))
        font = QtGui.QFont()
        font.setFamily("Bai Jamjuree")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lbl_date.setFont(font)
        self.lbl_date.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
                                    "font: 12pt \"Bai Jamjuree\";")
        self.lbl_date.setObjectName("lbl_date")
        self.lbl_time = QtWidgets.QLabel(Dialog)
        self.lbl_time.setGeometry(QtCore.QRect(40, 190, 381, 41))
        font = QtGui.QFont()
        font.setFamily("Bai Jamjuree")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lbl_time.setFont(font)
        self.lbl_time.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
                                    "font: 12pt \"Bai Jamjuree\";")
        self.lbl_time.setObjectName("lbl_time")
        self.lbl_member = QtWidgets.QLabel(Dialog)
        self.lbl_member.setGeometry(QtCore.QRect(40, 260, 381, 41))
        font = QtGui.QFont()
        font.setFamily("Bai Jamjuree")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lbl_member.setFont(font)
        self.lbl_member.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
                                      "font: 12pt \"Bai Jamjuree\";")
        self.lbl_member.setObjectName("lbl_member")
        self.tbro_description = QtWidgets.QTextBrowser(Dialog)
        self.tbro_description.setGeometry(QtCore.QRect(40, 330, 381, 101))
        self.tbro_description.setStyleSheet("font: 12pt \"Bai Jamjuree\";\n"
                                            "background-color: rgba(255, 255, 255, 0);\n"
                                            "border: 0px;")
        self.tbro_description.setObjectName("tbro_description")
        self.btn_viewMember = QtWidgets.QPushButton(Dialog)
        self.btn_viewMember.setGeometry(QtCore.QRect(320, 260, 111, 41))
        self.btn_viewMember.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
                                          "font: 12pt \"ZCOOL QingKe HuangYou\";\n"
                                          "color: rgb(85, 85, 255);\n"
                                          "border-radius: 10px;\n"
                                          "border: 2px solid rgb(85, 85, 255);")
        self.btn_viewMember.setObjectName("btn_viewMember")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.this_dialog = Dialog
        self.ShowActivityDetail()

        self.btn_cancelActivity.clicked.connect(self.CancelActivity)
        self.btn_viewMember.clicked.connect(self.ViewActivityMember)
        self.btn_back.clicked.connect(self.BackToShopActivity)

    def __init__(self, passData):
        self.userData = passData['userData']
        activityList = am.FetchActivityList({'_id': passData['activityID']})
        self.activityData: None
        for i in activityList:
            self.activityData = i
            break

    def ShowActivityDetail(self):
        self.lbl_title.setText(self.activityData['activityName'])
        self.lbl_date.setText(self.activityData['date'])
        self.lbl_time.setText("{} - {}".format(self.activityData['startTime'], self.activityData['endTime']))
        self.lbl_member.setText("{} / {}".format(self.activityData['currentPlayer'], self.activityData['maxPlayer']))
        self.tbro_description.setText(self.activityData['description'])

    def ViewActivityMember(self):
        activityData = {'activityName': self.activityData['activityName'],
                        'maxPlayer': self.activityData['maxPlayer'],
                        'joinedPlayerID': self.activityData['joinedPlayerID']}
        am.OpenNewWindowDialog(Shop_ActivityMember, passData=activityData)

    def CancelActivity(self):
        reply = am.ShowConfirmBox("Cancel Activity",
                                  "Cancel Activity [{}].\nAre you sure ?".format(self.activityData['activityName']))

        if reply:
            try:
                am.DeleteActivity(self.activityData['_id'])
                am.ShowMessageBox("Cancel Activity",
                                  "Cancel Activity [{}]\nSuccessful !!".format(self.activityData['activityName']),
                                  QMessageBox.Information)
                self.BackToShopActivity()
            except:
                am.ShowMessageBox("Cancel Activity",
                                  "Cancel Activity [{}]\nFailed !!\nPlease try again !!".format(
                                      self.activityData['activityName']),
                                  QMessageBox.Critical)

    def BackToShopActivity(self):
        am.ChangeWindowDialog(self.this_dialog, Shop_ActivityList, passData=self.userData)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Board Game Community"))
        self.lbl_title.setText(_translate("Dialog", "**ACTIVITY NAME**"))
        self.btn_cancelActivity.setText(_translate("Dialog", "Cancel Activity"))
        self.btn_back.setText(_translate("Dialog", "Back"))
        self.label_10.setText(_translate("Dialog", "Description"))
        self.label_11.setText(_translate("Dialog", "Date and Time"))
        self.label_12.setText(_translate("Dialog", "Time"))
        self.label_14.setText(_translate("Dialog", "Member"))
        self.lbl_date.setText(_translate("Dialog", "**DD-MMM-YY**"))
        self.lbl_time.setText(_translate("Dialog", "**START TIME - END TIME**"))
        self.lbl_member.setText(_translate("Dialog", "**00 / 00**"))
        self.tbro_description.setHtml(_translate("Dialog",
                                                 "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                                 "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                                 "p, li { white-space: pre-wrap; }\n"
                                                 "</style></head><body style=\" font-family:\'Bai Jamjuree\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
                                                 "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">**DESCRIPTION</p>\n"
                                                 "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">DESCRIPTION**</p></body></html>"))
        self.btn_viewMember.setText(_translate("Dialog", "View Member"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
