# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/Shop_ActivityList.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QTableWidgetItem, QAbstractItemView, QMessageBox

import ApplicationManagement as am
import Login, Shop_CreateActivity, Shop_ActivityDetail, Shop_ShopDetail


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(470, 710)
        Dialog.setFixedSize(470, 710)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/Icon.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        Dialog.setWindowIcon(icon)
        font = QtGui.QFont()
        font.setFamily("ZCOOL QingKe HuangYou")
        font.setPointSize(12)
        Dialog.setFont(font)
        Dialog.setStyleSheet("background-color: rgb(235, 235, 255);")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 90, 331, 41))
        font = QtGui.QFont()
        font.setFamily("ZCOOL QingKe HuangYou")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
                                   "color: rgb(36, 36, 111);\n"
                                   "font: 20pt \"ZCOOL QingKe HuangYou\";")
        self.label_3.setTextFormat(QtCore.Qt.AutoText)
        self.label_3.setObjectName("label_3")
        self.tbl_activitiesList = QtWidgets.QTableWidget(Dialog)
        self.tbl_activitiesList.setGeometry(QtCore.QRect(20, 200, 431, 441))
        self.tbl_activitiesList.setStyleSheet("font: 10pt \"Bai Jamjuree\";\n"
                                              "background-color: rgb(255, 255, 255);")
        self.tbl_activitiesList.setObjectName("tbl_activitiesList")
        self.tbl_activitiesList.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.tbl_activitiesList.setColumnCount(0)
        self.tbl_activitiesList.setRowCount(0)
        self.btn_editShop = QtWidgets.QPushButton(Dialog)
        self.btn_editShop.setGeometry(QtCore.QRect(330, 20, 121, 41))
        self.btn_editShop.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
                                        "font: 12pt \"ZCOOL QingKe HuangYou\";\n"
                                        "color: rgb(85, 85, 255);\n"
                                        "border-radius: 10px;\n"
                                        "border: 2px solid rgb(85, 85, 255);")
        self.btn_editShop.setObjectName("btn_editShop")
        self.lbl_shopName = QtWidgets.QLabel(Dialog)
        self.lbl_shopName.setGeometry(QtCore.QRect(20, 20, 291, 41))
        font = QtGui.QFont()
        font.setFamily("Bai Jamjuree")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lbl_shopName.setFont(font)
        self.lbl_shopName.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
                                        "color: rgb(36, 36, 111);\n"
                                        "font: 14pt \"Bai Jamjuree\";")
        self.lbl_shopName.setTextFormat(QtCore.Qt.AutoText)
        self.lbl_shopName.setObjectName("lbl_shopName")
        self.btn_logOut = QtWidgets.QPushButton(Dialog)
        self.btn_logOut.setGeometry(QtCore.QRect(360, 90, 91, 31))
        self.btn_logOut.setStyleSheet("background-color:  rgba(0, 0, 0, 0);\n"
                                      "color: rgb(200, 9, 19);\n"
                                      "font: 10pt \"ZCOOL QingKe HuangYou\";\n"
                                      "border-radius: 10px;\n"
                                      "border: 2px solid rgb(200, 9, 19);")
        self.btn_logOut.setObjectName("btn_logOut")
        self.btn_viewActivities = QtWidgets.QPushButton(Dialog)
        self.btn_viewActivities.setGeometry(QtCore.QRect(20, 650, 211, 41))
        self.btn_viewActivities.setStyleSheet("background-color: rgb(85, 85, 255);\n"
                                              "color: rgb(255, 255, 255);\n"
                                              "font: 12pt \"ZCOOL QingKe HuangYou\";\n"
                                              "border: 2px solid rgb(85, 85, 255);\n"
                                              "border-radius: 10px;")
        self.btn_viewActivities.setObjectName("btn_viewActivities")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(17, 120, 431, 16))
        self.line.setStyleSheet("color: rgb(36, 36, 111);\n"
                                "background-color: rgba(255, 255, 255, 0);")
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(4)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.ltxt_searchBar = QtWidgets.QLineEdit(Dialog)
        self.ltxt_searchBar.setGeometry(QtCore.QRect(20, 150, 431, 41))
        self.ltxt_searchBar.setPlaceholderText("Search...")
        self.ltxt_searchBar.setStyleSheet("font: 12pt \"Bai Jamjuree\";\n"
                                          "border: 2px solid rgb(85, 85, 255);\n"
                                          "background-color: rgba(255, 255, 255, 0);\n"
                                          "border-radius: 10px ;")
        self.ltxt_searchBar.setObjectName("ltxt_searchBar")
        self.btn_createActivity = QtWidgets.QPushButton(Dialog)
        self.btn_createActivity.setGeometry(QtCore.QRect(240, 650, 211, 41))
        self.btn_createActivity.setStyleSheet("background-color: rgb(85, 85, 255);\n"
                                              "color: rgb(255, 255, 255);\n"
                                              "font: 12pt \"ZCOOL QingKe HuangYou\";\n"
                                              "border: 2px solid rgb(85, 85, 255);\n"
                                              "border-radius: 10px;")
        self.btn_createActivity.setObjectName("btn_createActivity")
        self.label_3.raise_()
        self.tbl_activitiesList.raise_()
        self.btn_editShop.raise_()
        self.lbl_shopName.raise_()
        self.btn_logOut.raise_()
        self.btn_viewActivities.raise_()
        self.line.raise_()
        self.ltxt_searchBar.raise_()
        self.btn_createActivity.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.this_dialog = Dialog
        self.SetupShopDetail()
        self.DisplayActivity({'shopID': self.userData['_id']})

        self.ltxt_searchBar.textChanged.connect(self.Search)
        self.btn_viewActivities.clicked.connect(self.ViewSelectedActivity)
        self.btn_createActivity.clicked.connect(self.CreateActivity)
        self.btn_editShop.clicked.connect(self.EditShopDetail)
        self.btn_logOut.clicked.connect(self.LogOut)

    def __init__(self, passData):
        self.userData = passData

    def SetupShopDetail(self):
        self.lbl_shopName.setText(self.userData['shopName'])

    def DisplayActivity(self, conditional):
        activityList = am.FetchActivityList(conditional)

        self.tbl_activitiesList.setRowCount(activityList.__len__())
        self.tbl_activitiesList.setColumnCount(4)

        self.tbl_activitiesList.setHorizontalHeaderItem(0, QTableWidgetItem("_ID"))
        self.tbl_activitiesList.setHorizontalHeaderItem(1, QTableWidgetItem("ACTIVITY"))
        self.tbl_activitiesList.setHorizontalHeaderItem(2, QTableWidgetItem("MEMBER"))
        self.tbl_activitiesList.setHorizontalHeaderItem(3, QTableWidgetItem("DATE"))
        self.tbl_activitiesList.setColumnHidden(0, True)

        row = 0
        for i in activityList:
            self.tbl_activitiesList.setItem(row, 0, QTableWidgetItem("{}".format(i['_id'])))
            self.tbl_activitiesList.setItem(row, 1, QTableWidgetItem("{}".format(i['activityName'])))
            self.tbl_activitiesList.setItem(row, 2,
                                            QTableWidgetItem("{} / {}".format(i['currentPlayer'], i['maxPlayer'])))
            self.tbl_activitiesList.setItem(row, 3, QTableWidgetItem("{}".format(i['date'])))
            row += 1

        self.tbl_activitiesList.resizeColumnsToContents()

    def Search(self):
        searchText = self.ltxt_searchBar.text()
        conditional = {'$and': [{'shopID': self.userData['_id']},
                                {'$or': [{'activityName': {'$regex': searchText}},
                                         {'date': {'$regex': searchText}}]}]}
        self.DisplayActivity(conditional)

    def ViewSelectedActivity(self):
        selectedActivity = self.tbl_activitiesList.currentRow()
        if selectedActivity != -1:
            activityID = am.ToObjectId(self.tbl_activitiesList.item(selectedActivity, 0).text())
            am.ChangeWindowDialog(self.this_dialog, Shop_ActivityDetail, passData={'activityID': activityID,
                                                                               'userData': self.userData})
        else:
            am.ShowMessageBox("View Activity", "Please Select Activity !!", QMessageBox.Critical)

    def CreateActivity(self):
        am.ChangeWindowDialog(self.this_dialog, Shop_CreateActivity, passData=self.userData)

    def EditShopDetail(self):
        am.ChangeWindowDialog(self.this_dialog, Shop_ShopDetail, passData=self.userData)

    def LogOut(self):
        am.ChangeWindowDialog(self.this_dialog, Login)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Board Game Community"))
        self.label_3.setText(_translate("Dialog", "Your Activities"))
        self.btn_editShop.setText(_translate("Dialog", "Edit Shop"))
        self.lbl_shopName.setText(_translate("Dialog", "**SHOP NAME**"))
        self.btn_logOut.setText(_translate("Dialog", "Log Out"))
        self.btn_viewActivities.setText(_translate("Dialog", "View Selected Activities"))
        self.btn_createActivity.setText(_translate("Dialog", "Create New Activity"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
