# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/User_AllPartyList.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QTableWidgetItem, QAbstractItemView, QMessageBox

import ApplicationManagement as am
import Login, User_PartyDetail, User_CreateParty, User_ActivityList


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(470, 710)
        Dialog.setFixedSize(470, 710)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/Icon.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        Dialog.setWindowIcon(icon)
        font = QtGui.QFont()
        font.setFamily("ZCOOL QingKe HuangYou")
        font.setPointSize(12)
        Dialog.setFont(font)
        Dialog.setStyleSheet("background-color: rgb(235, 255, 235);")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 90, 331, 41))
        font = QtGui.QFont()
        font.setFamily("ZCOOL QingKe HuangYou")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
                                   "color: rgb(0, 100, 76);\n"
                                   "font: 20pt \"ZCOOL QingKe HuangYou\";")
        self.label_3.setTextFormat(QtCore.Qt.AutoText)
        self.label_3.setObjectName("label_3")
        self.tbl_partyList = QtWidgets.QTableWidget(Dialog)
        self.tbl_partyList.setGeometry(QtCore.QRect(20, 250, 431, 391))
        self.tbl_partyList.setStyleSheet("font: 10pt \"Bai Jamjuree\";\n"
                                         "background-color: rgb(255, 255, 255);")
        self.tbl_partyList.setObjectName("tbl_partyList")
        self.tbl_partyList.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.tbl_partyList.setColumnCount(0)
        self.tbl_partyList.setRowCount(0)
        self.btn_shopActivity = QtWidgets.QPushButton(Dialog)
        self.btn_shopActivity.setGeometry(QtCore.QRect(330, 20, 121, 41))
        self.btn_shopActivity.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
                                            "font: 12pt \"ZCOOL QingKe HuangYou\";\n"
                                            "color: rgb(0, 154, 49);\n"
                                            "border-radius: 10px;\n"
                                            "border: 2px solid rgb(0, 154, 49);")
        self.btn_shopActivity.setObjectName("btn_shopActivity")
        self.lbl_username = QtWidgets.QLabel(Dialog)
        self.lbl_username.setGeometry(QtCore.QRect(20, 20, 291, 41))
        font = QtGui.QFont()
        font.setFamily("Bai Jamjuree")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lbl_username.setFont(font)
        self.lbl_username.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
                                        "color: rgb(0, 100, 76);\n"
                                        "font: 14pt \"Bai Jamjuree\";")
        self.lbl_username.setTextFormat(QtCore.Qt.AutoText)
        self.lbl_username.setObjectName("lbl_username")
        self.btn_logOut = QtWidgets.QPushButton(Dialog)
        self.btn_logOut.setGeometry(QtCore.QRect(360, 90, 91, 31))
        self.btn_logOut.setStyleSheet("background-color:  rgba(0, 0, 0, 0);\n"
                                      "color: rgb(200, 9, 19);\n"
                                      "font: 10pt \"ZCOOL QingKe HuangYou\";\n"
                                      "border-radius: 10px;\n"
                                      "border: 2px solid rgb(200, 9, 19);")
        self.btn_logOut.setObjectName("btn_logOut")
        self.btn_viewParty = QtWidgets.QPushButton(Dialog)
        self.btn_viewParty.setGeometry(QtCore.QRect(20, 650, 211, 41))
        self.btn_viewParty.setStyleSheet("background-color: rgb(0, 154, 49);\n"
                                         "color: rgb(255, 255, 255);\n"
                                         "font: 12pt \"ZCOOL QingKe HuangYou\";\n"
                                         "border-radius: 10px;\n"
                                         "border: 2px solid rgb(0, 154, 49);")
        self.btn_viewParty.setObjectName("btn_viewParty")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(17, 120, 431, 16))
        self.line.setStyleSheet("color: rgb(0, 100, 76);\n"
                                "background-color: rgba(255, 255, 255, 0);")
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(4)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.ltxt_searchBar = QtWidgets.QLineEdit(Dialog)
        self.ltxt_searchBar.setGeometry(QtCore.QRect(20, 150, 431, 41))
        self.ltxt_searchBar.setPlaceholderText("Search...")
        self.ltxt_searchBar.setStyleSheet("font: 12pt \"Bai Jamjuree\";\n"
                                          "border: 2px solid rgb(0, 154, 49);\n"
                                          "background-color: rgba(255, 255, 255, 0);\n"
                                          "border-radius: 10px ;")
        self.ltxt_searchBar.setObjectName("ltxt_searchBar")
        self.lbl_fullname = QtWidgets.QLabel(Dialog)
        self.lbl_fullname.setGeometry(QtCore.QRect(20, 60, 291, 21))
        font = QtGui.QFont()
        font.setFamily("Bai Jamjuree")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lbl_fullname.setFont(font)
        self.lbl_fullname.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
                                        "color: rgb(0, 100, 76);\n"
                                        "font: 10pt \"Bai Jamjuree\";")
        self.lbl_fullname.setTextFormat(QtCore.Qt.AutoText)
        self.lbl_fullname.setObjectName("lbl_fullname")
        self.btn_createParty = QtWidgets.QPushButton(Dialog)
        self.btn_createParty.setGeometry(QtCore.QRect(240, 650, 211, 41))
        self.btn_createParty.setStyleSheet("background-color: rgb(0, 154, 49);\n"
                                           "color: rgb(255, 255, 255);\n"
                                           "font: 12pt \"ZCOOL QingKe HuangYou\";\n"
                                           "border-radius: 10px;\n"
                                           "border: 2px solid rgb(0, 154, 49);")
        self.btn_createParty.setObjectName("btn_createParty")
        self.rbtn_joinedParty = QtWidgets.QRadioButton(Dialog)
        self.rbtn_joinedParty.setGeometry(QtCore.QRect(340, 210, 101, 20))
        self.rbtn_joinedParty.setStyleSheet("font: 10pt \"ZCOOL QingKe HuangYou\";\n"
                                            "background-color: rgba(255, 255, 255, 0);\n"
                                            "color: rgb(0, 100, 76);")
        self.rbtn_joinedParty.setObjectName("rbtn_joinedParty")
        self.rbtn_allParty = QtWidgets.QRadioButton(Dialog)
        self.rbtn_allParty.setGeometry(QtCore.QRect(30, 210, 91, 20))
        self.rbtn_allParty.setStyleSheet("font: 10pt \"ZCOOL QingKe HuangYou\";\n"
                                         "background-color: rgba(255, 255, 255, 0);\n"
                                         "color: rgb(0, 100, 76);")
        self.rbtn_allParty.setChecked(True)
        self.rbtn_allParty.setObjectName("rbtn_allParty")
        self.rbtn_newParty = QtWidgets.QRadioButton(Dialog)
        self.rbtn_newParty.setGeometry(QtCore.QRect(180, 210, 111, 20))
        self.rbtn_newParty.setStyleSheet("font: 10pt \"ZCOOL QingKe HuangYou\";\n"
                                         "background-color: rgba(255, 255, 255, 0);\n"
                                         "color: rgb(0, 100, 76);")
        self.rbtn_newParty.setObjectName("rbtn_newParty")
        self.label_3.raise_()
        self.tbl_partyList.raise_()
        self.btn_shopActivity.raise_()
        self.lbl_username.raise_()
        self.btn_logOut.raise_()
        self.btn_viewParty.raise_()
        self.line.raise_()
        self.ltxt_searchBar.raise_()
        self.lbl_fullname.raise_()
        self.btn_createParty.raise_()
        self.rbtn_joinedParty.raise_()
        self.rbtn_allParty.raise_()
        self.rbtn_newParty.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.this_dialog = Dialog
        self.SetUserDetail()
        self.DisplayParty({})

        self.ltxt_searchBar.textChanged.connect(self.Search)
        self.rbtn_allParty.clicked.connect(self.Search)
        self.rbtn_newParty.clicked.connect(self.Search)
        self.rbtn_joinedParty.clicked.connect(self.Search)
        self.btn_createParty.clicked.connect(self.CreateParty)
        self.btn_viewParty.clicked.connect(self.ViewSelectedParty)
        self.btn_shopActivity.clicked.connect(self.ViewShopActivity)
        self.btn_logOut.clicked.connect(self.LogOut)

    def __init__(self, passData):
        self.userData = passData

    def SetUserDetail(self):
        self.lbl_username.setText(self.userData['username'])
        self.lbl_fullname.setText(self.userData['fullname'])

    def DisplayParty(self, conditional):
        partyList = am.FetchPartyList(conditional)

        self.tbl_partyList.setRowCount(partyList.__len__())
        self.tbl_partyList.setColumnCount(6)

        self.tbl_partyList.setHorizontalHeaderItem(0, QTableWidgetItem("_ID"))
        self.tbl_partyList.setHorizontalHeaderItem(1, QTableWidgetItem("ACTIVITY"))
        self.tbl_partyList.setHorizontalHeaderItem(2, QTableWidgetItem("MEMBER"))
        self.tbl_partyList.setHorizontalHeaderItem(3, QTableWidgetItem("DATE"))
        self.tbl_partyList.setHorizontalHeaderItem(4, QTableWidgetItem("LOCATION"))
        self.tbl_partyList.setHorizontalHeaderItem(5, QTableWidgetItem("OWNER"))
        self.tbl_partyList.setColumnHidden(0, True)

        row = 0
        for i in partyList:
            self.tbl_partyList.setItem(row, 0, QTableWidgetItem("{}".format(i['_id'])))
            self.tbl_partyList.setItem(row, 1, QTableWidgetItem("{}".format(i['partyName'])))
            self.tbl_partyList.setItem(row, 2, QTableWidgetItem("{} / {}".format(i['currentPlayer'], i['maxPlayer'])))
            self.tbl_partyList.setItem(row, 3, QTableWidgetItem("{}".format(i['date'])))
            self.tbl_partyList.setItem(row, 4, QTableWidgetItem("{}".format(i['shopName'])))
            self.tbl_partyList.setItem(row, 5, QTableWidgetItem("{}".format(i['creatorUsername'])))
            row += 1

        self.tbl_partyList.resizeColumnsToContents()

    def Search(self):
        searchText = self.ltxt_searchBar.text()
        textConditional = [{'partyName': {'$regex': searchText}},
                           {'date': {'$regex': searchText}},
                           {'shopName': {'$regex': searchText}},
                           {'creatorUsername': {'$regex': searchText}}]
        conditional = {}
        if self.rbtn_allParty.isChecked():
            conditional = {'$or': textConditional}
        else:
            if self.rbtn_joinedParty.isChecked():
                conditional = {'$and': [{'joinedPlayerID': {'$in': [self.userData['_id']]}},
                                        {'$or': textConditional}]}
            elif self.rbtn_newParty.isChecked():
                conditional = {'$and': [{'joinedPlayerID': {'$nin': [self.userData['_id']]}},
                                        {'$or': textConditional}]}
        self.DisplayParty(conditional)

    def ViewSelectedParty(self):
        selectedParty = self.tbl_partyList.currentRow()
        if selectedParty != -1:
            partyID = am.ToObjectId(self.tbl_partyList.item(selectedParty, 0).text())
            am.ChangeWindowDialog(self.this_dialog, User_PartyDetail, passData={'partyID': partyID,
                                                                                'userData': self.userData})
        else:
            am.ShowMessageBox("View Party", "Please Select Party !!", QMessageBox.Critical)

    def CreateParty(self):
        am.ChangeWindowDialog(self.this_dialog, User_CreateParty, passData=self.userData)

    def ViewShopActivity(self):
        am.ChangeWindowDialog(self.this_dialog, User_ActivityList, passData=self.userData)

    def LogOut(self):
        am.ChangeWindowDialog(self.this_dialog, Login)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Board Game Community"))
        self.label_3.setText(_translate("Dialog", "All Party"))
        self.btn_shopActivity.setText(_translate("Dialog", "Shop Activity"))
        self.lbl_username.setText(_translate("Dialog", "**USERNAME**"))
        self.btn_logOut.setText(_translate("Dialog", "Log Out"))
        self.btn_viewParty.setText(_translate("Dialog", "View Selected Party"))
        self.lbl_fullname.setText(_translate("Dialog", "**FULL NAME**"))
        self.btn_createParty.setText(_translate("Dialog", "Create New Party"))
        self.rbtn_joinedParty.setText(_translate("Dialog", "Joined Party"))
        self.rbtn_allParty.setText(_translate("Dialog", "All Party"))
        self.rbtn_newParty.setText(_translate("Dialog", "Not Join Party"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
