# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/User_MemberList.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QTableWidgetItem

import ApplicationManagement as am


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(470, 710)
        Dialog.setFixedSize(470, 710)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/Icon.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        Dialog.setWindowIcon(icon)
        font = QtGui.QFont()
        font.setFamily("ZCOOL QingKe HuangYou")
        font.setPointSize(12)
        Dialog.setFont(font)
        Dialog.setStyleSheet("background-color: rgb(235, 255, 235);")
        self.lbl_title = QtWidgets.QLabel(Dialog)
        self.lbl_title.setGeometry(QtCore.QRect(20, 20, 431, 61))
        font = QtGui.QFont()
        font.setFamily("ZCOOL QingKe HuangYou")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lbl_title.setFont(font)
        self.lbl_title.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
                                     "color: rgb(0, 100, 76);\n"
                                     "font: 16pt \"Bai Jamjuree\";")
        self.lbl_title.setTextFormat(QtCore.Qt.AutoText)
        self.lbl_title.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_title.setObjectName("lbl_title")
        self.btn_back = QtWidgets.QPushButton(Dialog)
        self.btn_back.setGeometry(QtCore.QRect(360, 660, 91, 31))
        self.btn_back.setStyleSheet("background-color:  rgba(0, 0, 0, 0);\n"
                                    "color: rgb(200, 9, 19);\n"
                                    "font: 12pt \"ZCOOL QingKe HuangYou\";\n"
                                    "border-radius: 10px;\n"
                                    "border: 2px solid rgb(200, 9, 19);")
        self.btn_back.setObjectName("btn_back")
        self.label_14 = QtWidgets.QLabel(Dialog)
        self.label_14.setGeometry(QtCore.QRect(40, 90, 211, 31))
        font = QtGui.QFont()
        font.setFamily("ZCOOL QingKe HuangYou")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
                                    "font: 12pt \"ZCOOL QingKe HuangYou\";\n"
                                    "color: rgb(0, 100, 76);")
        self.label_14.setObjectName("label_14")
        self.lbl_member = QtWidgets.QLabel(Dialog)
        self.lbl_member.setGeometry(QtCore.QRect(40, 120, 381, 41))
        font = QtGui.QFont()
        font.setFamily("Bai Jamjuree")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lbl_member.setFont(font)
        self.lbl_member.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
                                      "font: 12pt \"Bai Jamjuree\";")
        self.lbl_member.setObjectName("lbl_member")
        self.tbl_member = QtWidgets.QTableWidget(Dialog)
        self.tbl_member.setGeometry(QtCore.QRect(20, 160, 431, 491))
        self.tbl_member.setStyleSheet("font: 10pt \"Bai Jamjuree\";\n"
                                           "background-color: rgb(255, 255, 255);")
        self.tbl_member.setObjectName("tbl_member")
        self.tbl_member.setColumnCount(0)
        self.tbl_member.setRowCount(0)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.this_dialog = Dialog
        self.SetEventDetail()
        self.DisplayMember()

        self.btn_back.clicked.connect(self.BackToEventDetail)

    def __init__(self, passData):
        self.eventData = passData

    def SetEventDetail(self):
        self.lbl_title.setText(self.eventData['eventName'])
        self.lbl_member.setText(
            "{} / {}".format(self.eventData['joinedPlayerID'].__len__(), self.eventData['maxPlayer']))

    def DisplayMember(self):
        memberList = am.FetchPlayerList({'_id': {'$in': self.eventData['joinedPlayerID']}})

        self.tbl_member.setRowCount(memberList.__len__())
        self.tbl_member.setColumnCount(2)

        self.tbl_member.setHorizontalHeaderItem(0, QTableWidgetItem("USERNAME"))
        self.tbl_member.setHorizontalHeaderItem(1, QTableWidgetItem("TELEPHONE"))

        row = 0
        for i in memberList:
            self.tbl_member.setItem(row, 0, QTableWidgetItem("{}".format(i['username'])))
            self.tbl_member.setItem(row, 1, QTableWidgetItem("{}".format(i['phone'])))
            row += 1

    def BackToEventDetail(self):
        self.this_dialog.close()

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Board Game Community"))
        self.lbl_title.setText(_translate("Dialog", "**EVENT NAME**"))
        self.btn_back.setText(_translate("Dialog", "Back"))
        self.label_14.setText(_translate("Dialog", "Member"))
        self.lbl_member.setText(_translate("Dialog", "**00 / 00**"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
