# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/User_JoinedPartyList.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QTableWidgetItem, QAbstractItemView, QMessageBox

import ApplicationManagement as am
import Login, User_ActivityDetail, User_PartyList


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(470, 710)
        Dialog.setFixedSize(470, 710)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/Icon.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        Dialog.setWindowIcon(icon)
        font = QtGui.QFont()
        font.setFamily("ZCOOL QingKe HuangYou")
        font.setPointSize(12)
        Dialog.setFont(font)
        Dialog.setStyleSheet("background-color: rgb(235, 255, 235);")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 90, 331, 41))
        font = QtGui.QFont()
        font.setFamily("ZCOOL QingKe HuangYou")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
                                   "color: rgb(0, 100, 76);\n"
                                   "font: 20pt \"ZCOOL QingKe HuangYou\";")
        self.label_3.setTextFormat(QtCore.Qt.AutoText)
        self.label_3.setObjectName("label_3")
        self.tbl_activitiesList = QtWidgets.QTableWidget(Dialog)
        self.tbl_activitiesList.setGeometry(QtCore.QRect(20, 250, 431, 391))
        self.tbl_activitiesList.setStyleSheet("font: 10pt \"Bai Jamjuree\";\n"
                                              "background-color: rgb(255, 255, 255);")
        self.tbl_activitiesList.setObjectName("tbl_activitiesList")
        self.tbl_activitiesList.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.tbl_activitiesList.setColumnCount(0)
        self.tbl_activitiesList.setRowCount(0)
        self.btn_findParty = QtWidgets.QPushButton(Dialog)
        self.btn_findParty.setGeometry(QtCore.QRect(330, 20, 121, 41))
        self.btn_findParty.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
                                         "font: 12pt \"ZCOOL QingKe HuangYou\";\n"
                                         "color: rgb(0, 154, 49);\n"
                                         "border-radius: 10px;\n"
                                         "border: 2px solid rgb(0, 154, 49);")
        self.btn_findParty.setObjectName("btn_findParty")
        self.lbl_username = QtWidgets.QLabel(Dialog)
        self.lbl_username.setGeometry(QtCore.QRect(20, 20, 291, 41))
        font = QtGui.QFont()
        font.setFamily("Bai Jamjuree")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lbl_username.setFont(font)
        self.lbl_username.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
                                        "color: rgb(0, 100, 76);\n"
                                        "font: 14pt \"Bai Jamjuree\";")
        self.lbl_username.setTextFormat(QtCore.Qt.AutoText)
        self.lbl_username.setObjectName("lbl_username")
        self.btn_logOut = QtWidgets.QPushButton(Dialog)
        self.btn_logOut.setGeometry(QtCore.QRect(360, 90, 91, 31))
        self.btn_logOut.setStyleSheet("background-color:  rgba(0, 0, 0, 0);\n"
                                      "color: rgb(200, 9, 19);\n"
                                      "font: 10pt \"ZCOOL QingKe HuangYou\";\n"
                                      "border-radius: 10px;\n"
                                      "border: 2px solid rgb(200, 9, 19);")
        self.btn_logOut.setObjectName("btn_logOut")
        self.btn_viewActivity = QtWidgets.QPushButton(Dialog)
        self.btn_viewActivity.setGeometry(QtCore.QRect(20, 650, 201, 41))
        self.btn_viewActivity.setStyleSheet("background-color: rgb(0, 154, 49);\n"
                                            "color: rgb(255, 255, 255);\n"
                                            "font: 12pt \"ZCOOL QingKe HuangYou\";\n"
                                            "border-radius: 10px;\n"
                                            "border: 2px solid rgb(0, 154, 49);")
        self.btn_viewActivity.setObjectName("btn_viewActivity")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(17, 120, 431, 16))
        self.line.setStyleSheet("color: rgb(0, 100, 76);\n"
                                "background-color: rgba(255, 255, 255, 0);")
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(4)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.ltxt_searchBar = QtWidgets.QLineEdit(Dialog)
        self.ltxt_searchBar.setGeometry(QtCore.QRect(20, 150, 431, 41))
        self.ltxt_searchBar.setPlaceholderText("Search...")
        self.ltxt_searchBar.setStyleSheet("font: 12pt \"Bai Jamjuree\";\n"
                                          "border: 2px solid rgb(0, 154, 49);\n"
                                          "background-color: rgba(255, 255, 255, 0);\n"
                                          "border-radius: 10px ;")
        self.ltxt_searchBar.setObjectName("ltxt_searchBar")
        self.lbl_fullname = QtWidgets.QLabel(Dialog)
        self.lbl_fullname.setGeometry(QtCore.QRect(20, 60, 291, 21))
        font = QtGui.QFont()
        font.setFamily("Bai Jamjuree")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lbl_fullname.setFont(font)
        self.lbl_fullname.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
                                        "color: rgb(0, 100, 76);\n"
                                        "font: 10pt \"Bai Jamjuree\";")
        self.lbl_fullname.setTextFormat(QtCore.Qt.AutoText)
        self.lbl_fullname.setObjectName("lbl_fullname")
        self.rbtn_allActivity = QtWidgets.QRadioButton(Dialog)
        self.rbtn_allActivity.setGeometry(QtCore.QRect(30, 210, 91, 20))
        self.rbtn_allActivity.setStyleSheet("font: 10pt \"ZCOOL QingKe HuangYou\";\n"
                                            "background-color: rgba(255, 255, 255, 0);\n"
                                            "color: rgb(0, 100, 76);")
        self.rbtn_allActivity.setChecked(True)
        self.rbtn_allActivity.setObjectName("rbtn_allActivity")
        self.rbtn_newActivity = QtWidgets.QRadioButton(Dialog)
        self.rbtn_newActivity.setGeometry(QtCore.QRect(160, 210, 131, 20))
        self.rbtn_newActivity.setStyleSheet("font: 10pt \"ZCOOL QingKe HuangYou\";\n"
                                            "background-color: rgba(255, 255, 255, 0);\n"
                                            "color: rgb(0, 100, 76);")
        self.rbtn_newActivity.setObjectName("rbtn_newActivity")
        self.rbtn_joinedActivity = QtWidgets.QRadioButton(Dialog)
        self.rbtn_joinedActivity.setGeometry(QtCore.QRect(320, 210, 121, 20))
        self.rbtn_joinedActivity.setStyleSheet("font: 10pt \"ZCOOL QingKe HuangYou\";\n"
                                               "background-color: rgba(255, 255, 255, 0);\n"
                                               "color: rgb(0, 100, 76);")
        self.rbtn_joinedActivity.setObjectName("rbtn_joinedActivity")
        self.label_3.raise_()
        self.tbl_activitiesList.raise_()
        self.btn_findParty.raise_()
        self.lbl_username.raise_()
        self.btn_logOut.raise_()
        self.btn_viewActivity.raise_()
        self.line.raise_()
        self.ltxt_searchBar.raise_()
        self.lbl_fullname.raise_()
        self.rbtn_allActivity.raise_()
        self.rbtn_newActivity.raise_()
        self.rbtn_joinedActivity.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.this_dialog = Dialog
        self.SetUserDetail()
        self.DisplayActivity({})

        self.ltxt_searchBar.textChanged.connect(self.Search)
        self.rbtn_allActivity.clicked.connect(self.Search)
        self.rbtn_newActivity.clicked.connect(self.Search)
        self.rbtn_joinedActivity.clicked.connect(self.Search)
        self.btn_viewActivity.clicked.connect(self.ViewSelectedActivity)
        self.btn_findParty.clicked.connect(self.ViewParty)
        self.btn_logOut.clicked.connect(self.LogOut)

    def __init__(self, passData):
        self.userData = passData

    def SetUserDetail(self):
        self.lbl_username.setText(self.userData['username'])
        self.lbl_fullname.setText(self.userData['fullname'])

    def DisplayActivity(self, conditional):
        activityList = am.FetchActivityList(conditional)

        self.tbl_activitiesList.setRowCount(activityList.__len__())
        self.tbl_activitiesList.setColumnCount(5)

        self.tbl_activitiesList.setHorizontalHeaderItem(0, QTableWidgetItem("_ID"))
        self.tbl_activitiesList.setHorizontalHeaderItem(1, QTableWidgetItem("ACTIVITY"))
        self.tbl_activitiesList.setHorizontalHeaderItem(2, QTableWidgetItem("MEMBER"))
        self.tbl_activitiesList.setHorizontalHeaderItem(3, QTableWidgetItem("DATE"))
        self.tbl_activitiesList.setHorizontalHeaderItem(4, QTableWidgetItem("LOCATION"))
        self.tbl_activitiesList.setColumnHidden(0, True)

        row = 0
        for i in activityList:
            self.tbl_activitiesList.setItem(row, 0, QTableWidgetItem("{}".format(i['_id'])))
            self.tbl_activitiesList.setItem(row, 1, QTableWidgetItem("{}".format(i['activityName'])))
            self.tbl_activitiesList.setItem(row, 2,
                                            QTableWidgetItem("{} / {}".format(i['currentPlayer'], i['maxPlayer'])))
            self.tbl_activitiesList.setItem(row, 3, QTableWidgetItem("{}".format(i['date'])))
            self.tbl_activitiesList.setItem(row, 4, QTableWidgetItem("{}".format(i['shopName'])))
            row += 1

        self.tbl_activitiesList.resizeColumnsToContents()

    def Search(self):
        searchText = self.ltxt_searchBar.text()
        textConditional = [{'activityName': {'$regex': searchText}},
                           {'date': {'$regex': searchText}},
                           {'shopName': {'$regex': searchText}}]
        conditional = {}
        if self.rbtn_allActivity.isChecked():
            conditional = {'$or': textConditional}
        else:
            if self.rbtn_joinedActivity.isChecked():
                conditional = {'$and': [{'joinedPlayerID': {'$in': [self.userData['_id']]}},
                                        {'$or': textConditional}]}
            elif self.rbtn_newActivity.isChecked():
                conditional = {'$and': [{'joinedPlayerID': {'$nin': [self.userData['_id']]}},
                                        {'$or': textConditional}]}
        self.DisplayActivity(conditional)

    def ViewSelectedActivity(self):
        selectedActivity = self.tbl_activitiesList.currentRow()
        if selectedActivity != -1:
            activityID = am.ToObjectId(self.tbl_activitiesList.item(selectedActivity, 0).text())
            am.ChangeWindowDialog(self.this_dialog, User_ActivityDetail, passData={'activityID': activityID,
                                                                                   'userData': self.userData})
        else:
            am.ShowMessageBox("View Activity", "Please Select Activity !!", QMessageBox.Critical)

    def ViewParty(self):
        am.ChangeWindowDialog(self.this_dialog, User_PartyList, passData=self.userData)

    def LogOut(self):
        am.ChangeWindowDialog(self.this_dialog, Login)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Board Game Community"))
        self.label_3.setText(_translate("Dialog", "Shop Activity"))
        self.btn_findParty.setText(_translate("Dialog", "Find A Party"))
        self.lbl_username.setText(_translate("Dialog", "**USERNAME**"))
        self.btn_logOut.setText(_translate("Dialog", "Log Out"))
        self.btn_viewActivity.setText(_translate("Dialog", "View Selected Activity"))
        self.lbl_fullname.setText(_translate("Dialog", "**FULL NAME**"))
        self.rbtn_allActivity.setText(_translate("Dialog", "All Activity"))
        self.rbtn_newActivity.setText(_translate("Dialog", "Not Join Activity"))
        self.rbtn_joinedActivity.setText(_translate("Dialog", "Joined Activity"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
