# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/User_CreateParty.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QDate
from PyQt5.QtWidgets import QMessageBox

import ApplicationManagement as am
import User_PartyList, User_ShopDetail


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(470, 710)
        Dialog.setFixedSize(470, 710)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/Icon.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        Dialog.setWindowIcon(icon)
        font = QtGui.QFont()
        font.setFamily("ZCOOL QingKe HuangYou")
        font.setPointSize(12)
        Dialog.setFont(font)
        Dialog.setStyleSheet("background-color: rgb(235, 255, 235);")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 20, 431, 41))
        font = QtGui.QFont()
        font.setFamily("ZCOOL QingKe HuangYou")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
                                   "color: rgb(0, 100, 76);\n"
                                   "font: 20pt \"ZCOOL QingKe HuangYou\";")
        self.label_3.setTextFormat(QtCore.Qt.AutoText)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.btn_createParty = QtWidgets.QPushButton(Dialog)
        self.btn_createParty.setGeometry(QtCore.QRect(40, 610, 391, 41))
        self.btn_createParty.setStyleSheet("background-color: rgb(0, 154, 49);\n"
                                           "color: rgb(255, 255, 255);\n"
                                           "font: 12pt \"ZCOOL QingKe HuangYou\";\n"
                                           "border-radius: 10px;\n"
                                           "border: 2px solid rgb(0, 154, 49);")
        self.btn_createParty.setObjectName("btn_createParty")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(40, 70, 211, 31))
        font = QtGui.QFont()
        font.setFamily("ZCOOL QingKe HuangYou")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
                                   "font: 12pt \"ZCOOL QingKe HuangYou\";\n"
                                   "color: rgb(0, 100, 76);")
        self.label_8.setObjectName("label_8")
        self.ltxt_title = QtWidgets.QLineEdit(Dialog)
        self.ltxt_title.setGeometry(QtCore.QRect(40, 100, 391, 41))
        self.ltxt_title.setStyleSheet("font: 12pt \"Bai Jamjuree\";\n"
                                      "border: 0px;\n"
                                      "border-bottom: 2px solid rgb(0, 154, 49);\n"
                                      "background-color: rgba(255, 255, 255, 0)")
        self.ltxt_title.setText("")
        self.ltxt_title.setObjectName("ltxt_title")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(40, 140, 211, 31))
        font = QtGui.QFont()
        font.setFamily("ZCOOL QingKe HuangYou")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
                                   "font: 12pt \"ZCOOL QingKe HuangYou\";\n"
                                   "color: rgb(0, 100, 76);")
        self.label_9.setObjectName("label_9")
        self.cbx_shop = QtWidgets.QComboBox(Dialog)
        self.cbx_shop.setGeometry(QtCore.QRect(40, 170, 291, 41))
        self.cbx_shop.setStyleSheet("QComboBox {\n"
                                    "font: 12pt \"Bai Jamjuree\";\n"
                                    "border: 0px;\n"
                                    "border-bottom: 2px solid rgb(0, 154, 49);\n"
                                    "background-color: rgba(255, 255, 255, 0);\n"
                                    "}")
        self.cbx_shop.setObjectName("cbx_shop")
        self.btn_back = QtWidgets.QPushButton(Dialog)
        self.btn_back.setGeometry(QtCore.QRect(360, 660, 91, 31))
        self.btn_back.setStyleSheet("background-color:  rgba(0, 0, 0, 0);\n"
                                    "color: rgb(200, 9, 19);\n"
                                    "font: 12pt \"ZCOOL QingKe HuangYou\";\n"
                                    "border-radius: 10px;\n"
                                    "border: 2px solid rgb(200, 9, 19);")
        self.btn_back.setObjectName("btn_back")
        self.btn_viewShop = QtWidgets.QPushButton(Dialog)
        self.btn_viewShop.setGeometry(QtCore.QRect(340, 170, 101, 41))
        self.btn_viewShop.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
                                        "font: 12pt \"ZCOOL QingKe HuangYou\";\n"
                                        "color: rgb(0, 154, 49);\n"
                                        "border-radius: 10px;\n"
                                        "border: 2px solid rgb(0, 154, 49);")
        self.btn_viewShop.setObjectName("btn_viewShop")
        self.txt_description = QtWidgets.QTextEdit(Dialog)
        self.txt_description.setGeometry(QtCore.QRect(40, 450, 391, 91))
        self.txt_description.setStyleSheet("font: 12pt \"Bai Jamjuree\";\n"
                                           "border: 0px;\n"
                                           "border-bottom: 2px solid rgb(0, 154, 49);\n"
                                           "background-color: rgba(255, 255, 255, 0)")
        self.txt_description.setObjectName("txt_description")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(40, 420, 211, 31))
        font = QtGui.QFont()
        font.setFamily("ZCOOL QingKe HuangYou")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
                                    "font: 12pt \"ZCOOL QingKe HuangYou\";\n"
                                    "color: rgb(0, 100, 76);")
        self.label_10.setObjectName("label_10")
        self.dedt_date = QtWidgets.QDateEdit(Dialog)
        self.dedt_date.setGeometry(QtCore.QRect(40, 240, 391, 41))
        self.dedt_date.setMinimumDate(QDate.currentDate())
        self.dedt_date.setDisplayFormat("dd-MMM-yyyy")
        self.dedt_date.setStyleSheet("font: 12pt \"Bai Jamjuree\";\n"
                                     "border: 0px;\n"
                                     "border-bottom: 2px solid rgb(0, 154, 49);\n"
                                     "background-color: rgba(255, 255, 255, 0)")
        self.dedt_date.setObjectName("dedt_date")
        self.tedt_startTime = QtWidgets.QTimeEdit(Dialog)
        self.tedt_startTime.setGeometry(QtCore.QRect(40, 310, 161, 41))
        self.tedt_startTime.setStyleSheet("font: 12pt \"Bai Jamjuree\";\n"
                                          "border: 0px;\n"
                                          "border-bottom: 2px solid rgb(0, 154, 49);\n"
                                          "background-color: rgba(255, 255, 255, 0)")
        self.tedt_startTime.setObjectName("tedt_startTime")
        self.tedt_endTime = QtWidgets.QTimeEdit(Dialog)
        self.tedt_endTime.setGeometry(QtCore.QRect(270, 310, 161, 41))
        self.tedt_endTime.setStyleSheet("font: 12pt \"Bai Jamjuree\";\n"
                                        "border: 0px;\n"
                                        "border-bottom: 2px solid rgb(0, 154, 49);\n"
                                        "background-color: rgba(255, 255, 255, 0)")
        self.tedt_endTime.setObjectName("tedt_endTime")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(40, 210, 211, 31))
        font = QtGui.QFont()
        font.setFamily("ZCOOL QingKe HuangYou")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
                                    "font: 12pt \"ZCOOL QingKe HuangYou\";\n"
                                    "color: rgb(0, 100, 76);")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(40, 280, 211, 31))
        font = QtGui.QFont()
        font.setFamily("ZCOOL QingKe HuangYou")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
                                    "font: 12pt \"ZCOOL QingKe HuangYou\";\n"
                                    "color: rgb(0, 100, 76);")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(Dialog)
        self.label_13.setGeometry(QtCore.QRect(210, 320, 51, 31))
        font = QtGui.QFont()
        font.setFamily("ZCOOL QingKe HuangYou")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
                                    "font: 12pt \"ZCOOL QingKe HuangYou\";\n"
                                    "color: rgb(0, 100, 76);")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.sbx_maxPeople = QtWidgets.QSpinBox(Dialog)
        self.sbx_maxPeople.setGeometry(QtCore.QRect(40, 380, 391, 41))
        self.sbx_maxPeople.setStyleSheet("font: 12pt \"Bai Jamjuree\";\n"
                                         "border: 0px;\n"
                                         "border-bottom: 2px solid rgb(0, 154, 49);\n"
                                         "background-color: rgba(255, 255, 255, 0)")
        self.sbx_maxPeople.setMinimum(2)
        self.sbx_maxPeople.setMaximum(999)
        self.sbx_maxPeople.setObjectName("sbx_maxPeople")
        self.label_14 = QtWidgets.QLabel(Dialog)
        self.label_14.setGeometry(QtCore.QRect(40, 350, 211, 31))
        font = QtGui.QFont()
        font.setFamily("ZCOOL QingKe HuangYou")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
                                    "font: 12pt \"ZCOOL QingKe HuangYou\";\n"
                                    "color: rgb(0, 100, 76);")
        self.label_14.setObjectName("label_14")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.this_dialog = Dialog
        self.FetchShopList()

        self.btn_viewShop.clicked.connect(self.ViewShop)
        self.btn_createParty.clicked.connect(self.CreateParty)
        self.btn_back.clicked.connect(self.BackToPartyList)

    def __init__(self, passData):
        self.userData = passData

    def FetchShopList(self):
        shopList = am.FetchShopList({})
        for i in shopList:
            self.cbx_shop.addItem(i['shopName'], i)

    def ViewShop(self):
        shopData = self.cbx_shop.currentData()
        am.OpenNewWindowDialog(User_ShopDetail, passData=shopData)

    def CreateParty(self):
        partyData = {'partyName': self.ltxt_title.text(),
                     'creatorID': self.userData['_id'],
                     'shopID': self.cbx_shop.currentData()['_id'],
                     'date': self.dedt_date.date().toPyDate(),
                     'startTime': self.tedt_startTime.time().toPyTime(),
                     'endTime': self.tedt_endTime.time().toPyTime(),
                     'maxPlayer': int(self.sbx_maxPeople.text()),
                     'description': self.txt_description.toPlainText()}

        checkPartyData, checkDetail = am.CheckCreateParty(partyData)

        if checkPartyData:
            try:
                am.InsertNewParty(partyData)
                am.ShowMessageBox("Create New Party", checkDetail, QMessageBox.Information)
                am.ChangeWindowDialog(self.this_dialog, User_PartyList, passData=self.userData)
            except Exception as e:
                checkDetail = "Error !!\nCannot Create New Party !!\nPlease Try Again !!"
                am.ShowMessageBox("Create New Party", checkDetail, QMessageBox.Critical)
                print(e)
        else:
            am.ShowMessageBox("Create New Party", checkDetail, QMessageBox.Critical)

    def BackToPartyList(self):
        am.ChangeWindowDialog(self.this_dialog, User_PartyList, passData=self.userData)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Board Game Community"))
        self.label_3.setText(_translate("Dialog", "Create New Party"))
        self.btn_createParty.setText(_translate("Dialog", "Create New Party"))
        self.label_8.setText(_translate("Dialog", "Title"))
        self.label_9.setText(_translate("Dialog", "Shop Party Location"))
        self.btn_back.setText(_translate("Dialog", "Back"))
        self.btn_viewShop.setText(_translate("Dialog", "View Shop"))
        self.label_10.setText(_translate("Dialog", "Description"))
        self.label_11.setText(_translate("Dialog", "Date"))
        self.label_12.setText(_translate("Dialog", "Time"))
        self.label_13.setText(_translate("Dialog", "To"))
        self.label_14.setText(_translate("Dialog", "Maximum People"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
