# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/RegisterMenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import ApplicationManagement as am
import Login, New_Player, New_ShopOwner


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(470, 710)
        Dialog.setFixedSize(470, 710)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/Icon.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        Dialog.setWindowIcon(icon)
        font = QtGui.QFont()
        font.setFamily("ZCOOL QingKe HuangYou")
        font.setPointSize(12)
        Dialog.setFont(font)
        Dialog.setStyleSheet(
            "background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.353234 rgba(235, 255, 235, 255), stop:1 rgba(215, 215, 255, 255));")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(40, 220, 391, 61))
        font = QtGui.QFont()
        font.setFamily("ZCOOL QingKe HuangYou")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
                                   "font: 20pt \"ZCOOL QingKe HuangYou\";\n"
                                   "color: rgb(0, 100, 76);")
        self.label_3.setTextFormat(QtCore.Qt.AutoText)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.btn_newPlayer = QtWidgets.QPushButton(Dialog)
        self.btn_newPlayer.setGeometry(QtCore.QRect(40, 320, 391, 41))
        self.btn_newPlayer.setStyleSheet("background-color: rgb(0, 154, 49);\n"
                                         "color: rgb(255, 255, 255);\n"
                                         "font: 12pt \"ZCOOL QingKe HuangYou\";\n"
                                         "border-radius: 10px;\n"
                                         "border: 2px solid rgb(0, 154, 49);")
        self.btn_newPlayer.setObjectName("btn_newPlayer")
        self.btn_newShopOwner = QtWidgets.QPushButton(Dialog)
        self.btn_newShopOwner.setGeometry(QtCore.QRect(40, 390, 391, 41))
        self.btn_newShopOwner.setStyleSheet("background-color: rgb(85, 85, 255);\n"
                                            "color: rgb(255, 255, 255);\n"
                                            "font: 12pt \"ZCOOL QingKe HuangYou\";\n"
                                            "border-radius: 10px;\n"
                                            "border: 2px solid rgb(85, 85, 255);")
        self.btn_newShopOwner.setObjectName("btn_newShopOwner")
        self.btn_back = QtWidgets.QPushButton(Dialog)
        self.btn_back.setGeometry(QtCore.QRect(360, 660, 91, 31))
        self.btn_back.setStyleSheet("background-color:  rgba(0, 0, 0, 0);\n"
                                    "color: rgb(200, 9, 19);\n"
                                    "font: 12pt \"ZCOOL QingKe HuangYou\";\n"
                                    "border-radius: 10px;\n"
                                    "border: 2px solid rgb(200, 9, 19);")
        self.btn_back.setObjectName("btn_back")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.this_dialog = Dialog

        self.btn_newPlayer.clicked.connect(self.OpenNewPlayerMenu)
        self.btn_newShopOwner.clicked.connect(self.OpenNewShopOwnerMenu)
        self.btn_back.clicked.connect(self.OpenLoginMenu)

    def OpenNewPlayerMenu(self):
        am.ChangeWindowDialog(self.this_dialog, New_Player)

    def OpenNewShopOwnerMenu(self):
        am.ChangeWindowDialog(self.this_dialog, New_ShopOwner)

    def OpenLoginMenu(self):
        am.ChangeWindowDialog(self.this_dialog, Login)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Board Game Community"))
        self.label_3.setText(_translate("Dialog", "Register Menu"))
        self.btn_newPlayer.setText(_translate("Dialog", "New Player"))
        self.btn_newShopOwner.setText(_translate("Dialog", "New Shop Owner"))
        self.btn_back.setText(_translate("Dialog", "Back"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
